### ISSUE TITLE
Support readline navigation

### ISSUE THREAD

**Issue by munk** [oakes/Nightcode#144]
I tried Nightcode today, and it looks great! The thing that jumped out at me though, and it's a dealbreaker, is that I had to use the arrow keys to get around, or click with my trackpad. I'm using a Mac, so I'm used to having at least a few readline commands available to move around in whatever editor I'm using, even if it's not natively supported.

It's kind of painful to have to navigate with the arrow keys. I understand that's a feature of Cocoa on OS X, but it would be great if Nightcode supported readline navigation, or at least a subset that let you jump around by words. I'd be open to something else clever, like a vim mode or something that could jump around expressions with a little intelligence. 

I'm sure this would make a lot of people switching from emacs (like me!) more comfortable too.

**Comment by daveloyall** [comment]
+1

Here is my user story: I read your 2.0.0 movie trailer.  "ok, why not?", I said.  Downloaded the jar.  Double clicked it.  That just works, great.  (I have multiple JREs and JDKs on this machine.  Lots of things just work on this machine!)  There's no installer, it's just running the IDE.

Ok, I don't know clojure, but I see a REPL here...  So I type this:

    (defun hello ()

That's exactly what I typed.  Then I hit RET because I intended to go to the next line to continue my defun...

As you know, multi-line doesn't work in the REPL, or if it does, it's bound to some key other than RET.  Fine, that's not what I am posting here about.

None of these work to recall the previous line from REPL input for editing: `M-p`, `alt+p`, `arrow up`, etc.  That's a bug.  You need `rlwrap(1)`.

**Comment by oakes** [comment]
@daveloyall yep i still need to implement REPL history support, i will do that soon

**Comment by daveloyall** [comment]
p.s. `(defn hello [] '"hello")`

**Comment by oakes** [comment]
No plans to add vim-style editing features at this time so I will close for now.

**Comment by munk** [comment]
This isn't vim style editing, this is line navigation supported by most shells and all native osx applications. If anything, it's closer to emacs navigation.

Unfortunately, this will keep me from using Nightcode.

**Comment by daveloyall** [comment]
For what it is worth, I don't care what specific key bindings are used...

But surely these functions should be implemented: (not an exhaustive list)

* `recall-previous-from-history`
* `recall-next-from-history`
* `move-cursor-to-beginning-of-line`
* `move-cursor-to-end-of-line`
* `move-cursor-back-one-word`
* `move-cursor-forward-one-word`
* `kill-word-forward`
* `kill-word-backward`
* etc
