### ISSUE TITLE
Old edits reappearing,code rearanging?

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#152]
I'm not sure I can reproduce this, but I've, on one occasion, seen chunks of old coder reappearing down the file below the recent edits, and on another occasion a couple lines swapped places.
  
It could be something external external to the program messing with memory; but I thought I'd see if anyone else observed this kind of weirdness.

**Comment by oakes** [comment]
Interesting. I think the issue with lines swapping places may be because you accidentally typed `Alt + down arrow`, a paredit command. I'm actually completely replacing the paredit code with parinfer, so this will no longer occur in the next release.

**Comment by jconti** [comment]
I like the sounds of this change.  Thanks for the preview.  

BTW, I am relatively expert at emacs, and use it for stuff.  But I enjoy the simple experience of Nightcode so much I use it for half of my clojure code (I am not a full-time clojure person, however).

**Comment by oakes** [comment]
FYI I built a snapshot version of Nightcode with parinfer added in case either of you would like to try it out: https://github.com/oakes/Nightcode/releases/download/1.1.0-SNAPSHOT/nightcode-1.1.0-SNAPSHOT-standalone.jar

**Comment by jconti** [comment]
Spent the afternoon with the Parinfer snapshot.  Here are my initial reflections on the coding experience:
* Wow, Paredit but with a much lower barrier to entry.  Seems like a great addition, allowing intermediate Lispers access to the full power of sexp structured editing.  I'm certainly hooked.
* Parinfer is too simple to be self-evident :-)  I suspect having a button to turn it on and off, like Paredit was before, may be important for first timers and anyone already climatized to a normal editor experience (anyone who's used a word processor).

**Comment by oakes** [comment]
Thanks for the feedback @jconti. I uploaded a new snapshot last night (same link) that has some additional improvements, including supporting multiline select + tab better. Regarding a toggle button, I was hoping to avoid it. The reason Paredit currently has a toggle button is because I noticed beginners simply couldn't figure it out, so I had to keep it off by default -- and simply accept the inevitable mismatched parens that happen as a result. The exciting thing about Parinfer is that I am not afraid of making it the default, and it also prevents mismatched parens.

**Comment by jconti** [comment]
I will try the new snapshot.  Your idea is a good one.  Less buttons and modes are certainly better.

Though I didn't have mis-matched parens when using it, I often had broken let statements etc. because I hadn't very carefully indented nested expressions and my forms had floated out of a let or into the binding form and it was hard to see.  Also it is tricky because parens move to places where eyes are not currently focused, which makes it a little hard to figure out what has occurred (lots of use of ^Z and ^Y).

Parinfer seems like great feature in the end.  I think beginners can benefit from the paren matching for sure.

**Comment by NathanSmutz** [comment]
I haven't gotten to trying out the parinfer version yet; but just in case this is relevant:
I've had to occasionally turn off Paredit to fix unbalanced parens.  I think it was usually from a lopsided copy/paste.  Sometimes an unmatched quote throws off syntax highlighting in the REPL (again probably a copy/paste issue)  Is Parinfer proofed against these things?

**Comment by jconti** [comment]
Just wanted to get back here and comment on the Parinfer support.  The code just went to 1.3, and the Parinfer support is really awesome.  It is a whole new feel to coding lisp, and I am loving it.  Thank you!

**Comment by oakes** [comment]
@jconti great to hear! I just released version 1.2.0 which improves the indentation behavior so hopefully that makes it even nicer to use.
