### ISSUE TITLE
Bundled java not found in Windows 10

### ISSUE THREAD

**Issue by jarppe** [oakes/Nightcode#222]
I have fresh Windows 10 in VirtualBox, I install nightcode from bundled Nightcode-2.3.3.exe. I create a new project and click "Run". REPL console shows error message:

```
  Running...
  Cannot run program "java" (in directory "C:\Users\IEUser\Documents\foo"): CreateProcess
  error=2, The system cannot find the file specified

  === Finished ===
```

The bundle would be really useful for us, we're having ClojureBridge tomorrow and ease of install is very important for us.

I assumed that JDK is bundled? Perhaps I assumed wrong?

**Comment by oakes** [comment]
Only the JRE is bundled. Technically, Clojure can be compiled just with the JRE, but the bundled one doesn't automatically appear on your system's PATH so Nightcode's build commands won't find it. That's why you still unfortunately need an external JDK installation for them to work. Right now the bundled JRE is only there to run Nightcode itself.
