### ISSUE TITLE
REPL process doesn't stop on Windows

### ISSUE THREAD

**Issue by zenon** [oakes/Nightcode#59]
NightCode 0.1.6, Java 1.7.0_21, Window$ 7

After starting Nightcode, and do "Run with REPL" at my project, I have 4 JVMs up and running. That's impressive enough, but I got some problems later:

Alternative a)
If I now press "Run with REPL" again (maybe that should be prevented?), another JVM starts, and the REPL doesn't work anymore. (Does it still connect to another JVM?)

Alternative b)
When I kill Nightcode, one of the JVMs doesn't stop. 

I once heard about a Leiningen problem of that kind. Sadly I can't find it anymore.

**Comment by NathanSmutz** [comment]
I'm only seeing an orphaned java.exe instance when I click the [Stop] button from the nREPL.
I'm using Nightcode 0.4.7, Windows 7

When I click [Run with REPL], two new java.exe instances start.
If I type "exit" within the REPL, both new java.exe instances go away.
If I click [Stop] while the REPL is running, one instance goes away, and the other new java.exe instance remains.

(This seems to be a windows-only issue for me at least.  Everything shuts down fine in Linux)

**Comment by oakes** [comment]
I haven't noticed this issue in the new version of Nightcode. Please let me know if you do.

**Comment by joinr** [comment]
Revisiting this issue, since I was able to stumble upon it incidentally (not using 2.7.0, but replicated it in 2.7.0).  Note: this could be getting into some more arcane OS-level stuff, so it may be outside the scope of nightcode per se.

On my (admittedly dated, due to targeting a client work environment) setup, which includes:
Windows 10, Java 1.8.0_181, I get an orphaned java.exe process that persists after [stop] is chosen from the ui.  Similar behavior (run-with-repl spawns a lein-driven repl, which spawns 2 java processes, of which lein's smaller launcher process (~143 mb though), sticks around).

If you (quit) from the REPL, everything gets cleaned up (I'm guessing the process magic in lein is working as intended).  If you [stop] from the ui, the causal path goes through the stop-process! function in nightcode.process,  which should be invoking .destroyForcibly, etc.  Somehow the lein launcher process is invisible or otherwise not responsive to destruction (on W10 at least).

I actually came across this when I was upgrading the old [nightcode 1.3.2 fork](https://github.com/joinr/Nightcode/tree/1.3.2a) I made to support [nightclub](https://github.com/joinr/nightclub/), namely to migrate to 1.10.  I noticed this problem crop up in testing [hadn't noticed it before, although it was likely there....].  I spent a week munging on it, messing with the process start/stop functions, trying to catch processes globally and ensure destruction on exit, etc.  Basically all for naught.  The process start/stop methods are effectively identical in 2.7.0; so it makes sense that the problem is reproduced.

Note: the simple work-around to not having orphaned processes is to (quit) instead of using [stop].  I also found that wiring up the [stop] button to feed "(quit)\n" to the repl's stdin worked well (in terms of preventing orphaned processes), but then you run into the problem of trying to stop runaway computations (e.g. (iterate inc 0)).  I tried adding a short timeout with a fallback to .destroy if the process was still alive after trying to send the repl input to quit, but the orphaned process just burned cycles.

Based on research into this, I'm not sure it's something the jvm has sufficient control over, and may require platform-specific hacks (even then....).  Assuming it can't be fixed, the net effect is you'll accrete lein-based java processes everytime you [stop] instead of (quit) from the project repl after run-with-repl, which are on the order of 143mb.....so do it enough times and the memory leak gets bad.  In practice, people may not even notice it (I didn't really, not until the recent testing....).

**Comment by oakes** [comment]
If you update your Java install to 9 or above, the issue should be fixed. Nightcode uses the new Java 9 Process API to stop the process, and uses reflection so it continues working on Java 8. The new Process API provides a more reliable way to stop processes IIRC.

**Comment by joinr** [comment]
That makes sense.  I've intentionally held off on moving past Java  8 until the production environment I have to target is allowed to transition (may not happen for some time, they may push the LTS as long a possible).  I'll just accept this a limitation of the platform for now (again, one that can be worked around - e.g. (quit) when possible, if you have to [stop], kill the orphans manually, etc.).  Thanks.

**Comment by oakes** [comment]
Actually if you use Nightcode via the windows installer it should work no matter what your system java version is, since it uses a private runtime. I'm guessing that you are running Nightcode via the jar file, is that correct?

**Comment by joinr** [comment]
Yes, I've always used the jar due to system restrictions (installer not whitelisted, but java preinstalled and accessible by user...).
