### ISSUE TITLE
Block comment?

### ISSUE THREAD

**Issue by CRHough** [oakes/Nightcode#66]
Hopefully I've just missed it but if not a command to comment the current selection (or current line/sexp if none selected) would be extremely useful.

**Comment by davidsavoie1** [comment]
Any update on this one since 2014? It's a feature I'm using a lot in other IDEs for other languages... Thanks!

**Comment by oakes** [comment]
I rewrote nightcode since this ticket was made, but the rewrite doesn't have the feature. I suggest putting `#_` on the line before a form to comment it out. That is a more precise way to comment and easier to undo. Here's an example:

```clojure
#_
(defn hello []
  (println "Hello, world!"))
```

I'll close this ticket because I don't have any plans to implement traditional block comments.
